One way of figuring out where the exception came from is to have
exception raise code call a noop runtime C function and set
breakpoints there.  Here are the diffs suggested by Perry to
accomplish this.

Index: Rtl/tortl.sml
===================================================================
RCS file: /afs/cs.cmu.edu/project/fox-1/research/cvsroot/ml96/Rtl/tortl.sml,v
retrieving revision 1.97
diff -b -B -r1.97 tortl.sml
472c472,477
<                 let val (I except,state) = xexp'(state,name,exp,Nil.TraceUnknown,NOTID)
---
>                 let val _ = add_instr(CALL{call_type = C_NORMAL,
>                                            func = LABEL' (ML_EXTERN_LABEL "RaiseStuff"),
>                                            args = [],
>                                            results = [],
>                                            save = getLocals()})
>                     val (I except,state) = xexp'(state,name,exp,Nil.TraceUnknown,NOTID)
478a484
>                     add_instr(ICOMMENT ("done raising exn " ^ (Name.var2string name)));
